services:
  mysql:
    container_name: mysqlPicPaySumplified
    image: mysql
    environment:
      MYSQL_DATABASE: picpaysimplified
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - '3306:3306'